---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-infrastructures
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/cnd2025-final/flux-infrastructures.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infrastructures
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-infrastructures
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructures

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-helmcharts
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-helmcharts
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructures
